namespace: traffic

resources:
  - namespace.yaml
  - kafka.yaml
  - spark-operator-complete-rbac.yaml
  - spark-s3-glacier-app.yaml
  - producer-deployment.yaml


images:
  - name: kafka-producer:dev
    newName: ghcr.io/achootrain/kafka-producer
    newTag: latest
  - name: spark-application:dev2
    newName: ghcr.io/achootrain/spark-application
    newTag: latest

commonLabels:
  app.kubernetes.io/part-of: traffic-system