apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-realtime-python
  namespace: traffic
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: ghcr.io/achootrain/spark-application:latest
  imagePullPolicy: Always
  imagePullSecrets:
    - ghcr-secret
  mainApplicationFile: local:///app/timeScaleDB.py
  # Core version hạ xuống 3.4.0
  sparkVersion: 3.4.0
  sparkConf:
    "spark.jars.ivy": "/tmp/.ivy2"
    "spark.jars": "local:///opt/spark/jars/hadoop-aws-3.3.4.jar,local:///opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar,local:///opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar,local:///opt/spark/jars/kafka-clients-3.5.1.jar,local:///opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar,local:///opt/spark/jars/commons-pool2-2.11.1.jar,local:///opt/spark/jars/postgresql-42.7.3.jar"
    # ------------------------------------------
    "spark.hadoop.hadoop.security.authentication": "simple"
    "spark.hadoop.fs.viewfs.enable": "false"
    "spark.driver.memoryOverhead": "1024m"
    "spark.executor.memoryOverhead": "1024m"
    
    # Cấu hình Jemalloc chống OOM (Giữ nguyên)
    "spark.driver.extraLibraryPath": "/usr/lib/x86_64-linux-gnu"
    "spark.executor.extraLibraryPath": "/usr/lib/x86_64-linux-gnu"
    "spark.kubernetes.driverEnv.LD_PRELOAD": "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
    "spark.kubernetes.executorEnv.LD_PRELOAD": "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
    
  driver:
    coreRequest: "100m"
    coreLimit: "300m"
    memory: 512m
    serviceAccount: default
    labels:
      version: "3.4.0"
    env:
      # Bắt buộc có dòng này để Jemalloc hoạt động
      - name: LD_PRELOAD
        value: "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
      - name: HOME
        value: "/tmp"
      - name: USER
        value: "spark"
      - name: HADOOP_USER_NAME
        value: "spark"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "kafka.traffic.svc.cluster.local:9092"
      - name: KAFKA_TOPIC
        value: "hugedata"
      - name: KAFKA_GROUP_ID
        value: "spark-realtime-group"
      - name: TIMESCALEDB_URL
        value: "jdbc:postgresql://timescaledb.traffic.svc.cluster.local:5432/traffic"
      - name: TIMESCALEDB_USER
        value: "postgres"
      - name: TIMESCALEDB_PASSWORD
        value: "postgres"
      - name: TIMESCALEDB_TABLE
        value: "traffic_metrics"
    securityContext:
      runAsUser: 185
      runAsGroup: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  executor:
    instances: 1
    coreRequest: "100m"
    coreLimit: "300m"
    memory: 512m
    labels:
      version: "3.4.0"
    env:
      # Bắt buộc có dòng này để Jemalloc hoạt động
      - name: LD_PRELOAD
        value: "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
      - name: HOME
        value: "/tmp"
      - name: USER
        value: "spark"
      - name: HADOOP_USER_NAME
        value: "spark"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "kafka.traffic.svc.cluster.local:9092"
      - name: KAFKA_TOPIC
        value: "hugedata"
      - name: KAFKA_GROUP_ID
        value: "spark-realtime-group"
      - name: TIMESCALEDB_URL
        value: "jdbc:postgresql://timescaledb.traffic.svc.cluster.local:5432/traffic"
      - name: TIMESCALEDB_USER
        value: "postgres"
      - name: TIMESCALEDB_PASSWORD
        value: "postgres"
      - name: TIMESCALEDB_TABLE
        value: "traffic_metrics"
    securityContext:
      runAsUser: 185
      runAsGroup: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault